pluginManagement {
    plugins {
        id 'org.springframework.boot' version providers.gradleProperty('springBootVersion').getOrElse('3.5.14')
    }
    repositories {
        maven { url = 'https://mirrors.huaweicloud.com/repository/maven/' }
        maven { url = 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        libs {
            from(files("../gradle/libs.versions.toml"))
        }
    }
}

rootProject.name = 'yudao-build-logic'
