plugins {
    id 'yudao-java'
}

dependencies {
    api project(':modules:yudao-common')
    api project(':modules:yudao-spring-boot-starter-security')
    api project(':modules:yudao-spring-boot-starter-mybatis')
    api project(':modules:yudao-spring-boot-starter-redis')
    compileOnly project(':modules:yudao-spring-boot-starter-rpc')
    compileOnly project(':modules:yudao-spring-boot-starter-job')
    compileOnly project(':modules:yudao-spring-boot-starter-mq')
    compileOnly 'org.springframework.kafka:spring-kafka'
    compileOnly 'org.springframework.amqp:spring-rabbit'
    compileOnly libs.rocketmq.spring
    api libs.guava
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
