plugins {
    id 'yudao-java'
}

dependencies {
    api project(':modules:yudao-common')
    api 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    api 'org.springframework.cloud:spring-cloud-starter-openfeign'
    api 'io.github.openfeign:feign-okhttp'
    implementation 'org.apache.httpcomponents:httpclient:4.5.14'
    implementation 'jakarta.validation:jakarta.validation-api'
}
