plugins {
    id 'yudao-java'
}

dependencies {
    api project(':modules:yudao-common')
    api 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    api 'org.springframework.cloud:spring-cloud-starter-openfeign'
    api 'io.github.openfeign:feign-okhttp'
    implementation libs.httpclient
    implementation 'jakarta.validation:jakarta.validation-api'
}
