plugins {
    id 'yudao-java'
}

dependencies {
    api project(':modules:yudao-common')
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    compileOnly 'org.springframework:spring-web'
    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    compileOnly libs.opentracing.util
    compileOnly libs.skywalking.trace
    compileOnly libs.skywalking.logback
    compileOnly libs.skywalking.opentracing
    compileOnly 'io.micrometer:micrometer-registry-prometheus'
    compileOnly libs.spring.boot.admin.client
}
