plugins {
    id 'yudao-spring-app'
}

springBoot {
    mainClass = 'cn.iocoder.yudao.server.YudaoServerApplication'
}

dependencies {
    implementation project(':modules:yudao-module-system-server')
    implementation project(':modules:yudao-module-infra-server')

    implementation project(':modules:yudao-spring-boot-starter-protection')
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config'

    implementation(project(':modules:yudao-spring-boot-starter-rpc')) {
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-starter-openfeign'
    }
    compileOnly 'jakarta.servlet:jakarta.servlet-api'
}
