plugins {
    id 'yudao-spring-app'
}

dependencies {
    implementation(project(':modules:yudao-module-system-api')) {
        exclude group: 'org.springdoc', module: 'springdoc-openapi-webmvc-core'
    }

    implementation 'org.springframework.cloud:spring-cloud-starter-gateway-server-webflux'
    implementation libs.knife4j.gateway
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config'
    implementation project(':modules:yudao-spring-boot-starter-monitor')
    implementation libs.guava
    implementation 'com.github.ben-manes.caffeine:caffeine'
}
